Add `IndexMap::from(array)` and `IndexSet::from(array)`
bluss/indexmap pull request #205
Opened 2021-10-21 21:08 UTC by rouge8

This patch adds `IndexMap::from(array)` and `IndexSet::from(array)` to match the API for `HashMap`, `HashSet`, etc. as of https://github.com/rust-lang/rust/pull/84111.

2021-12-02 22:00 UTC, rouge8 commented
@bluss bumping this now that CI is passing

2021-12-09 21:03 UTC, cuviper requested changes

2021-12-09 21:27 UTC, rouge8 commented on build.rs
> +    autocfg::new().emit_rustc_version(1, 51);
Should I bump it in this PR?

2021-12-09 23:11 UTC, cuviper commented on build.rs
> +    autocfg::new().emit_rustc_version(1, 51);
Well, I just looked at hashbrown and they may be bumping in the near future to MSRV 1.56, which we should probably follow when we do our bump. So... let's delay that decision for now.

2021-12-09 23:23 UTC, rouge8 commented on src/map.rs
> +#[cfg(all(has_std, rustc_1_51))]
done!

2022-01-06 18:21 UTC, cuviper requested changes
Just some cleanup on the `cfg`s.

2022-01-06 18:21 UTC, cuviper commented on src/map.rs
> +#[cfg(all(rustc_1_51))]
```suggestion
#[cfg(rustc_1_51)]
```

2022-01-06 18:21 UTC, cuviper commented on src/map.rs
> +    #[cfg(all(rustc_1_51))]
```suggestion
    #[cfg(rustc_1_51)]
```

2022-01-06 18:21 UTC, cuviper commented on src/set.rs
> +#[cfg(all(rustc_1_51))]
```suggestion
#[cfg(rustc_1_51)]
```

2022-01-06 18:21 UTC, cuviper commented on src/set.rs
> +    #[cfg(all(rustc_1_51))]
```suggestion
    #[cfg(rustc_1_51)]
```

2022-01-06 18:24 UTC, rouge8 commented
> Just some cleanup on the `cfg`s.

Oops, good catch. Fixed!

2022-01-06 18:32 UTC, cuviper commented
Oh, we do still need `std` because of `RandomState` -- that's too bad.

2022-01-06 18:35 UTC, rouge8 commented
> Oh, we do still need `std` because of `RandomState` -- that's too bad.

Ah okay. Reverted removing `has_std`.

2022-01-06 18:40 UTC, cuviper approved these changes
Thanks!

2022-01-06 18:41 UTC, merged